require("lazy").setup({
  spec = {
    { import = "plugins" },
    { import = "extra" },
  },
  defaults = { lazy = true, version = false },
  install = { colorscheme = { "lienchi", "habamax" } },
  dev = {
    path = "~/Workspace/neovim-plugins",
    patterns = { "2giosangmitom" },
  },
  ui = {
    backdrop = 90,
  },
  checker = { enabled = true },
  performance = {
    rtp = {
      disabled_plugins = {
        "2html_plugin",
        "tohtml",
        "getscript",
        "getscriptPlugin",
        "gzip",
        "logipat",
        "netrw",
        "netrwPlugin",
        "netrwSettings",
        "netrwFileHandlers",
        "matchit",
        "tar",
        "tarPlugin",
        "rrhelper",
        "spellfile_plugin",
        "vimball",
        "vimballPlugin",
        "zip",
        "zipPlugin",
        "tutor",
        "rplugin",
        "syntax",
        "synmenu",
        "optwin",
        "compiler",
        "bugreport",
        "ftplugin",
      },
    },
  },
})
